### ISSUE TITLE
Pad has unbound Persistant Volume Claims

### ISSUE THREAD

**Issue by salman-hayder** [davidcurrie/index2018#1]
I am facing this issue, when executing overrides.yaml, pod status is pending. When I describe pod it gives follwoing error.
pod has unbound PersistantVolumeClaims
![helm-jenkins](https://user-images.githubusercontent.com/40059719/43879932-bcb0273a-9bbf-11e8-88e2-a08b312a7645.png)

**Comment by davidcurrie** [comment]
please reopen if you're still seeing this
