### ISSUE TITLE
Problem in running the script

### ISSUE THREAD

**Issue by hitesh1907nayyar** [davidcurrie/index2018#2]
Hi,
I am facing problem in running the code. When I run on the Jenkins , I get below error:

+ docker build -t :80/hello:be6c2d1 .
invalid argument ":80/hello:be6c2d1" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
Can anybody please help ?

**Comment by davidcurrie** [comment]
Hi - are you running on `minikube` and, if so, have you enabled the `registry` add-on as per the instructions?

**Comment by davidcurrie** [comment]
fwiw: there is a newer version of this demo [here](https://github.com/davidcurrie/codeone2018)

**Comment by hitesh1907nayyar** [comment]
Hi David,
I am directly running this code on kubernates cluster with jenkins integrated. Can you please let me know what adjustments needs to be made so that it runs on kubernates cluster ?

I am trying to run this code on Amazon EKS cluster .

**Comment by hitesh1907nayyar** [comment]
Hi David, 
Can you please help ?

**Comment by davidcurrie** [comment]
Hi - sorry - missed the notification for your update yesterday. The following two lines in the Jenkinsfile are specific to running the demo in minikube as they are targeting its Docker registry addon:
https://github.com/davidcurrie/index2018/blob/master/Jenkinsfile#L45-L46

You need to update the repository variable to point at whatever you want to use for you Docker registry. If you're on EKS then the easiest thing to do is probably use ECR and then ensure that whatever IAM role your EKS node is running under has permission to write to that repository:
https://docs.aws.amazon.com/AmazonECR/latest/userguide/Repositories.html

**Comment by hitesh1907nayyar** [comment]
Hi David,

Thanks for your reply. For testing purpose can i make adjustment to the script so that it pushes the image to docker hub ? In the last helm deploy command it takes image from docker hub and deploy on it ?

**Comment by hitesh1907nayyar** [comment]
Hi David,

I did the following changes in your script to put the docker image on docker hub but getting the below error when deploy phase start using helm(Stage:Deploy):

[Pipeline] container
[Pipeline] {
[Pipeline] withCredentials
[Pipeline] {
[Pipeline] sh (hide)
+ docker login -u **** -p ****
/home/jenkins/workspace/demo@tmp/durable-296c4a84/script.sh: line 1: docker: not found
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // container


podTemplate(
    label: 'mypod', 
    inheritFrom: 'default',
    containers: [
        containerTemplate(
            name: 'golang', 
            image: 'golang:1.10-alpine',
            ttyEnabled: true,
            command: 'cat'
        ),
        containerTemplate(
            name: 'docker', 
            image: 'docker:18.02',
            ttyEnabled: true,
            command: 'cat'
        ),
        containerTemplate(
            name: 'helm', 
            image: 'ibmcom/k8s-helm:v2.6.0',
            ttyEnabled: true,
            command: 'cat'
        )
    ],
    volumes: [
        hostPathVolume(
            hostPath: '/var/run/docker.sock',
            mountPath: '/var/run/docker.sock'
        )
    ]
) {
    node('mypod') {
        def commitId
        stage ('Extract') {
            checkout scm
            commitId = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
        }
        stage ('Build') {
            container ('golang') {
                sh 'CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .'
            }
        }
        def repository
        stage ('Docker') {
            container ('docker') {
			    withCredentials([[$class: 'UsernamePasswordMultiBinding',
						credentialsId: '123456',
						usernameVariable: 'DOCKER_HUB_USER',
						passwordVariable: 'DOCKER_HUB_PASSWORD']]) {
					sh "docker build -t ${env.DOCKER_HUB_USER}/demo:${env.BUILD_NUMBER} ."
					sh "docker login -u ${env.DOCKER_HUB_USER} -p ${env.DOCKER_HUB_PASSWORD} "
					sh "docker push ${env.DOCKER_HUB_USER}/demo:${env.BUILD_NUMBER} "
				}
            }
        }
        stage ('Deploy') {
            container ('helm') {
			    withCredentials([[$class: 'UsernamePasswordMultiBinding',
						credentialsId: '123456',
						usernameVariable: 'DOCKER_HUB_USER',
						passwordVariable: 'DOCKER_HUB_PASSWORD']]){
					sh "docker login -u ${env.DOCKER_HUB_USER} -p ${env.DOCKER_HUB_PASSWORD} "	
                    sh "/helm init --client-only --skip-refresh"
                    sh "/helm upgrade --install --wait --set image.repository=${env.DOCKER_HUB_USER}/demo,image.tag=${env.BUILD_NUMBER} hello hello"
				}
            }
        }
    }
}

**Comment by davidcurrie** [comment]
You don't need the `docker login` in the Deploy stage (and there is no `docker` binary in that container hence the error). Instead, create a secret in the namespace you're deploying to with your registry credentials and then associate that with the default service account as an ImagePullSecret:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account

**Comment by hitesh1907nayyar** [comment]
Thanks David for all your help. I am able to create Jenkins File which is able to build and  deploy successfully. But the problem is http://hello.192.168.99.100.nip.io/ is giving an error of **hello.192.168.99.100.nip.io took too long to respond**. But when I use service type to be LoadBalancer instead of ClusterIP i get a response after hitting loadbalancerip :80. Can you please let me know as how can I troubleshoot with service type ClusterIP (values.yaml) as it is not working with application part.

**Comment by hitesh1907nayyar** [comment]
Hi David,

Any information on the above comment please?

**Comment by davidcurrie** [comment]
Hi again - glad you are making progress. My apologies again - I was offline for Friday and the w/e. As you've noted, the hostname for ingress is hardcoded into the values.yaml to work with a typical local minikube IP address. Why do you not want to use `LoadBalancer` as, except for the additional cost, that is typically the right thing to do in EKS.

**Comment by hitesh1907nayyar** [comment]
Hi David, 

Thanks for the reply.  I want to check out some of the ways through which i can check the exposed service on kubernates. LoadBalancer is working fine. Is there any way through which I can check the exposed service with service type as ClusterIP ?

**Comment by davidcurrie** [comment]
Two options if you want to stick with `ClusterIP`. The first is to continue to expose it via nginx ingress in which case you'll need the hostname in the values.yaml to match a DNS name that is pointing at an ELB for the cluster. You could continue to use `nip.io` for that DNS name and just replace the IP address with that for your ELB (a bit of a hack given that the IP can change). Alternatively, if you don't really want to expose the service but, instead, just access the application for development purposes, you can always use `kubectl port-forward` to access the running pod.

**Comment by hitesh1907nayyar** [comment]
Hi David, 

I have kept the DNS ip of LoadBalancer and changed the values in values.yaml file as below:
service:
******************************
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - hello.52.11.80.175.nip.io
*********************************************
But i am getting this error. (My release name is demo and hello is the chart name)
+ /helm upgrade --install --wait --set image.repository=****/demo,image.tag=56 demo hello
Error: UPGRADE FAILED: no Ingress with the name "demo-hello" found
[Pipeline] }
[Pipeline] // withCredentials

Are you aware as why this problem is coming ?

**Comment by davidcurrie** [comment]
Hmm - looks like Helm may have got confused because it's doing an upgrade but the previous release of the chart did not create an ingress resource. I'd just `helm delete --purge demo` and then try again.

**Comment by hitesh1907nayyar** [comment]
Thanks David. It is working now. I assume that i rollback to the failed version through helm which resulted in the above problem.  Once i deleted and recreated the build version it is working fine. Thanks for your help again.

**Comment by davidcurrie** [comment]
Glad to hear you got it working. As I said before, worth taking a look at the updated version [here](https://github.com/davidcurrie/codeone2018) as it has a couple of enhancements. Most notably, the use of kaniko for the Docker build to avoid the necessity to mount in the Docker socket from the host.
